# Generated by Django 4.2.26 on 2025-12-16 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_add_informe_fields_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='ingeniero_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'codigo_tipo_usuario': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
